// TODO: CREATE VARIABLES TO REFERENCE HTML ELEMENTS
// TODO: AND REQUIRED VALUES FOR GAME FUNCTIONALITY



// TODO: INITIALIZE PAGE WITH STARTER VALUES/IMAGES


// TODO: USER CLICKS START BUTTON TO START GAME - 
    
    // GAME FUNCTIONALITY
    // ==================
    // TODO: HIDE START BUTTON
    // TODO: SHOW CLICK BUTTON
    // TODO: SHOW KITTEN IMG AND DESCRIPTION

    // TODO: START TIMER AND SHOW ON PAGE


    // TODO: USER CLICKS 'CLICK ME' BUTTON --
    // TODO: INCREMENT THROUGH ARRAY OF KITTENS AND SCORE



    // END-GAME FUNCTIONALITY
    // ======================
    // TODO: GET USER INITIALS
    // TODO: SAVE USER/SCORE TO LOCALSTORAGE
    // TODO: RESET PAGE FOR NEW GAME AND SHOW SCORES
